### ISSUE TITLE
As tu deja gagner qq chose avec ce bot ? :)

### ISSUE THREAD

**Issue by Entwane** [j4rj4r/BotTwitter#1]
Salut,

j'utilise ton bot et j'aimerais juste savoir si tu a déjà gagner qq chose avec ce bot ;)

Merci

**Comment by j4rj4r** [comment]
Salut,

Oui pas mal, je mettrais un screen de ce que j'ai gagné dès que je pourrais.

**Comment by Entwane** [comment]
Cool 👍 

par contre il y a moyen de pas sélectionner des tweet déjà retweeter ?
Les commentaires ou mention ne marche pas chez moi, j'ai oublier un truc ?

**Comment by j4rj4r** [comment]
C'est juste à titre d'information le message comme quoi c'est déjà retweet, je m'en sers pour faire des logs mais je peux enlever si ça gêne.

Une ancienne version qu'il y a sur github, je met la dernière version lundi ou demain soir ( peu de chance )

**Comment by j4rj4r** [comment]
![screenshot_20181209-083023](https://user-images.githubusercontent.com/12416234/49694568-25ec3e00-fb8d-11e8-8195-13a184039a2a.jpg)

**Comment by Entwane** [comment]
Cool :) en combien de temps et avec combien de compte ?

**Comment by j4rj4r** [comment]
3 comptes , 3 semaines. 👍
