### ISSUE TITLE
Feedback version 2, partage d'idées pour perfectionner le bot

### ISSUE THREAD

**Issue by Erim32** [j4rj4r/BotTwitter#12]
Pour l'instant la version 2 fonctionne très bien, bravo et merci @j4rj4r 
J'en profite pour partager une idée d"évolution en consultant les différents types de concours. Je ne sais pas si c'est réellement pris en compte pour les tirages des gagnants des concours, mais certains concours demandent de commenter avec un message plus ou moins précis ( capture d'écran de quelque chose, prédire une valeur ou  un score, joindre le lien d'un produit désiré .... etc ).  

Une petite évolution supplémentaire possible du bot ,si elle te semble pertinente @j4rj4r  pourrait être dans la fonction commente() : 

**Gestion dynamique des demandes spécifiques des concours**
- Si le tweet du concours comprend les mots clés par exemple "Commente" et "avec" ( ou "Comment" "with" )  dans une même phrase  (regex retour à la ligne). 
- Alors le bot sélectionne un commentaire  aléatoire existant du post ( de préférence pas le plus récent et qui aurait au moins 1 like pour espérer un message crédible ), il recopierait exactement le même commentaire ( avec lien ou pièces jointes ), puis remplacerait les mentions qui ne sont pas dans le tweet original du concours par des membres de la liste à tagger. 
- Éventuellement il rajouterait le message aléatoire de tags des amis ( deja existant ) si c'est demandé par le concours en fin de ce message de commentaire. Puis posterait le commentaire qui normalement devrait être plus crédible vis a vis du contexte et des demandes.

C'est un simple partage d'idée à toi de voir si ça te semble pertinent, c'est ton projet avant tout 👍

**Comment by j4rj4r** [comment]
Salut, merci beaucoup pour ton retour ! 😃 

Pas mal l'idée, il y a moyen de l'implémenter dans une future mise à jour .
Si tu as d'autres idées hésite pas, je suis ouvert à toutes les propositions. 😋

**Comment by Erim32** [comment]
Salut, merci à toi pour ce super projet qui passe le test de Turing :) 

Un BUG je viens de remarquer, le bot en v2 semble avoir un problème avec la gestion des regex pour les tags d'amis, pour regex_detect_tag (https://github.com/j4rj4r/BotTwitter/blob/f834ef6eab28bf4479f28eb26d8c7053e6d6dead/retweet_giveaway.py#L35)   surtout s'il y a un smiley ou caractère avant ( je ne sais pas pour la gestion des majuscules) ? :

Exemples de cas ou il n'a pas tags des amis : 
"► Tag un ami "
"1. Taguez 2 personnes en commentaire sous ce tweet"
"-Coche blanche en gras#MENTIONNE 1 AMI(E) + TaG #cadeaunoel "
"Homme sourd TAG 2 potes"

Bonne soirée 👍

**Comment by j4rj4r** [comment]
J'ai remarqué aussi,  je vais voir pour modifier un peu le regex. Sinon j'ai fais un peu de ML pour détecter si il faut tag ou non mais faut que j'optimise un peu le model encore  (96% de précision pour l'instant)  😄 

tu gagnes des concours sinon ? 🎁

**Comment by Erim32** [comment]
Wow 96% c'est deja super bravo, il me tarde de voir. 👏
Quelques un avec la v1 mais rien de significatif pour l'instant et toi ? 🎁
