### ISSUE TITLE
Blacklistage des mots pour l'antibot non fonctionnel

### ISSUE THREAD

**Issue by HitoTech** [j4rj4r/BotTwitter#13]
Hello,

Il existe un paramètre appelé "words_to_blacklist_antibot" qui permet de blacklister certains mots dans les tweets que l'on souhaite copier sur les bots.

Cependant, après vérification, il s'avère que ce tableau de mots n'est jamais utilisé dans le code.

**Comment by Erim32** [comment]
Hello, exact : https://github.com/j4rj4r/BotTwitter/search?q=words_to_blacklist_antibot
