### ISSUE TITLE
issues with update

### ISSUE THREAD

**Issue by georgederr** [j4rj4r/BotTwitter#19]
<img width="802" alt="Screen Shot 2021-01-03 at 3 13 19 PM" src="https://user-images.githubusercontent.com/37233061/103487859-63583f80-4dd6-11eb-9d3b-18df791c5ff5.png">

When i run the updated files it doesn't give me errors of any kind nor does it do anything. it just hangs on a blank screen....

**Comment by georgederr** [comment]
not really broken... it still works but doesnt display anything

**Comment by HitoTech** [comment]
Hi, did you add the logging_level parameter in configuration.yml ?

**Comment by j4rj4r** [comment]
https://github.com/j4rj4r/BotTwitter/blob/b6310785b4133151a233c2dfc7a8642325119dca/configuration.yml.dist#L41

Replace "WARNING"  by "INFO" 😄

**Comment by georgederr** [comment]
yeah, I'm an idiot.  I realized what I did after I opened this.  Thanks,
