### ISSUE TITLE
Impossible de lancer le programme

### ISSUE THREAD

**Issue by VitoCorleone78** [j4rj4r/BotTwitter#22]
Bonjour, je reçois ce message d'erreur lorsque je lance le programme, je ne comprends pas ce que je dois changer pour empêcher cela. Si quelqu'un saurait comment résoudre le problème j'en serais très reconnaissant
![bottwitter](https://user-images.githubusercontent.com/77892777/105607771-26fa7c80-5da1-11eb-88d5-3bf0cd9cbfdb.JPG)

**Comment by j4rj4r** [comment]
Salut,

J'imagine qu'il y a un caractère spécial ou un chiffre au début de ton pseudo ?
Si oui c'est un problème dans le code (de comment on fait les requetes sql) faut que je trouve comment régler le problème ^^

**Comment by VitoCorleone78** [comment]
C'était ça il y avait un chiffre au début, merci beaucoup ça fonctionne parfaitement maintenant
