### ISSUE TITLE
incapacité de charger le fichier de config

### ISSUE THREAD

**Issue by pierre95872** [j4rj4r/BotTwitter#23]
Bonjour,

Voici ce qu'il me renvoie lorsque je tente de l’exécuter. Ayant de faible base voire aucune en informatique j’éprouve des difficultés .  
Pouvez vous m'aider?  
S'il vous plait je vous en serais très reconnaissant.

D'avance merci .

![twitter](https://user-images.githubusercontent.com/77988104/105749567-dcfdcc00-5f43-11eb-9b74-dc0600926037.PNG)

**Comment by j4rj4r** [comment]
Hello,

Il faut renommer le fichier "configuration.yml.dist" en "configuration.yml"

**Comment by pierre95872** [comment]
merci pour votre réponse, cependant je n'ai pas du renommer le fichier "configuration.yml.dist" en "configuration.yml" car je ne l'ai pas trouvé mais j'ai trouvé le fichier "configuration.yml" je me suis donc dit que mon ordinateur avait déjà changer le nom.

Cordialement.

**Comment by j4rj4r** [comment]
Ah bizarre, le fichier configuration est bien placé dans le meme répertoire que le main.py ?

**Comment by j4rj4r** [comment]
Dans le doute , il faudrait copier le contenu de configuration.yml et de refaire un fichier configuration.yml

**Comment by pierre95872** [comment]
oui ils sont bien placés dans le même répertoire.

déjà essaye cela ne fonctionne pas.

**Comment by kornflex** [comment]
Tu peux faire un "dir" sur ton répertoire pour voir ce qu'il y a dedans.

Autre chose, ton fichier configuration.yml ne comporte pas un espace foireux dans un coin ?
