### ISSUE TITLE
convert to lowercase giveaway_to_blacklist to compare with tweets

### ISSUE THREAD

**Issue by kornflex** [j4rj4r/BotTwitter#27]
Dans le configuration.yml par défaut, il y a la variable giveaway_to_blacklist qui contient entre autres : "nude".

Aujourd'hui, mon bot a participé a un concours dont le tweet est : 

```
Coucou je suis nouvelle sur Twitter n’hésite pas à me follow mes petits chérie Red heart

RT & FAV + FOLLOW = 1 Nude gratuite Peach
```

Les valeurs de giveaway_to_blacklist sont mise en uppercase dans le fichier main.py
Il faudrait donc faire de même pour le tweet a comparer.

J'y connais rien en python, mais je dirai que c'est à cette ligne : 
https://github.com/j4rj4r/BotTwitter/blob/1425a4678881f4e9b78779e7e6fd7aece16cdb60/BotTwitter/retweet_giveaway.py#L50

J'ai soumis la modif, mais à vérifier

**Comment by j4rj4r** [comment]
Tout est bon merci :p
