### ISSUE TITLE
Quelques questions

### ISSUE THREAD

**Issue by Hugo361** [j4rj4r/BotTwitter#3]
J'ai téléchargé l'ensemble des fichiers puis ai rentré les API keys et access Tokens et des erreurs subsistent : quand je lance le fichier main en cliquant direct dessus j'ai une erreur voir photo et lorsque je le lance depuis IDLE python(F5) j'ai une autre erreur si tu pouvais m'aider je t'en serais extrêmement reconnaissant ;)
![capture 2](https://user-images.githubusercontent.com/60072964/72686037-a26f8100-3af0-11ea-8056-c8b8fe9cbcca.PNG)
![Capture](https://user-images.githubusercontent.com/60072964/72686038-a26f8100-3af0-11ea-9fc1-de6181cf4f1c.PNG)

**Comment by j4rj4r** [comment]
Hello,

Le problème a été résolu directement par DM Twitter mais je fais quand meme un bilan ici pour tout le monde.

Pour la deuxième image,  il y avait un espace en trop dans les API Keys.
Pour la première image, Après une désinstallation et une re-installation de Python le problème a été résolu (surement une version différente entre la version utilsée par Windows et celle de l'IDE).
