### ISSUE TITLE
List flux rss

### ISSUE THREAD

**Issue by ephrael75** [j4rj4r/BotTwitter#35]
Bonjours 
Je n'arrive pas à trouver des flux rss pour les jeu concours tweeter france. pourriez vous m'en communiquer merci

ais

Hello
I can't find rss feeds for tweeting contests. could you tell me thank you

**Comment by j4rj4r** [comment]
Salut,

Regarde sur ce site, tu devrais trouver ton bonheur.
http://atlasflux.saynete.net/

**Comment by j4rj4r** [comment]
Ah je crois que tu as pas compris le principe du flux rss dans le bot. Les flux servent juste à tweet de temps en temps du texte pour pas que le bot ressemble à un bot sur twitter. Ou du moins qu'il ne ressemble pas à bot pour les sites de tirage.

**Comment by ephrael75** [comment]
Ah oui désolé, en effet, je croyais que les flux qui correspondait aux jeux concours devait être planqué dans des flux d’autres domaines. Merci beaucoup. En tout cas votre programme est vraiment super mais n’ayant d’habitude ni de python ni de Linux j’ai mis un peu de temps pour comprendre à l’installer.

Envoyé de mon iPhone
