### ISSUE TITLE
Blocage abonnement

### ISSUE THREAD

**Issue by mattttttttttttttttt** [j4rj4r/BotTwitter#6]
Il faudrais peut être mettre l'antibot à jour car au bout de 245 abonnement le compte ne peut plus s'abonner à des gens puis le lendemain sa marche mais très mal notamment à cause du code erreur 226

**Comment by j4rj4r** [comment]
Salut,

je suis entrain de faire une nouvelle version, je vais essayé de régler ce probleme.
Je met à jour l'issue une fois que le problème est réglé.

**Comment by mattttttttttttttttt** [comment]
Super, merci 😃

**Comment by Erim32** [comment]
Super projet merci, quelques petites ressources et feedbacks pour l'amélioration de la prochaine version :

Idées d'améliorations : 
- ajouter fichier de config pour definir les variables, et paramètres du bot, comptes ...
- ajouter une gestion de thread pour paralléliser l'exécution des bots si l'utilisateurs utilise plusieurs bots.

Pour passer sous les radars, voici les limites : https://help.twitter.com/fr/rules-and-policies/twitter-limits

Peut être une version instagram aussi un jour :) 
Bonne continuation et vivement les prochaine version, bonnes fêtes

**Comment by j4rj4r** [comment]
Salut, merci pour ton message 👍 

Je viens de mettre une nouvelle version sur le github. Il n'y a plus le probleme avec les abonnements, si on ne peut plus follow un message est affiché et on passe à l'étape suivant (bypass antibot ou prochain compte).

Il y a maintenant un fichier de configuration pour changer les réglages du bot. 👯 

Les threads arrivent bientot.

Bonnes fetes à toi aussi !
